language: csharp
services:
    - docker
before_install:
    - docker pull mcr.microsoft.com/dotnet/core/sdk:latest

before_script:
  - export PATH=$PATH:/home/travis/.dotnet/tools
    
jobs:
    include:
        - stage: build
            - script:
                - dotnet restore
                - dotnet test
                - dotnet build -c Release
        - stage: deploy
            - script:
                - dotnet publish -c Release
                - docker build -t honsproj HonoursProject/.
            
stages:
    - build
    - deploy