before_install: 
  - "docker pull mcr.microsoft.com/dotnet/core/sdk:latest"
before_script: 
  - "export PATH=$PATH:/home/travis/.dotnet/tools"
jobs: 
  include: 
    - 
      stage: "build - dotnet restore - dotnet test - dotnet build -c Release"
    - 
      stage: "deploy - dotnet publish -c Release - docker build -t honsproj HonoursProject/."
language: csharp
services: 
  - docker
stages: 
  - build
  - deploy
