version: '3.9'
services:
  model:
    build: .
    image: hnrs_model:latest
    container_name: Model
    ports:
      - "0.0.0.0:8000:8000"
    networks:
        -   hnrs_network
    environment:
      - graphing_service=Graphing:5000

  graphing:
    build: DataVisualising/.
    image: hnrs_graphing:latest
    container_name: Graphing
    ports:
      - "0.0.0.0:5000:5000"
    networks:
        -   hnrs_network


networks:
  hnrs_network:
    external: true